In [1]:
import numpy as np
from numpy import linalg as npla

def eig(A):
    eigenValues, eigenVectors = npla.eig(A)
    idx = np.argsort(eigenValues)
    eigenValues = eigenValues[idx]
    eigenVectors = eigenVectors[:,idx]
    return (eigenValues, eigenVectors)

# Ethylene
H=np.zeros([2,2])

H[0][1]=-1
H[1][0]=-1

print(H)

[[ 0. -1.]
 [-1.  0.]]


In [2]:
E,V=eig(H)

In [3]:
print(E)

[-1.  1.]


In [4]:
print(V)

[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


In [5]:
# 1,3-Butadiene
H=np.zeros([4,4])

for i in range(4):
    for j in range(4):
        if np.abs(i-j)==1:
            H[i][j]=-1

print(H)

[[ 0. -1.  0.  0.]
 [-1.  0. -1.  0.]
 [ 0. -1.  0. -1.]
 [ 0.  0. -1.  0.]]


In [6]:
E,V=eig(H)

In [7]:
print(E)

[-1.61803399 -0.61803399  0.61803399  1.61803399]


In [8]:
print(V)

[[ 0.37174803 -0.60150096  0.60150096 -0.37174803]
 [ 0.60150096 -0.37174803 -0.37174803  0.60150096]
 [ 0.60150096  0.37174803 -0.37174803 -0.60150096]
 [ 0.37174803  0.60150096  0.60150096  0.37174803]]


In [9]:
# Benzene
H=np.zeros([6,6])

for i in range(6):
    for j in range(6):
        if np.abs(i-j)==1:
            H[i][j]=-1
H[0][5]=-1
H[5][0]=-1
print(H)

[[ 0. -1.  0.  0.  0. -1.]
 [-1.  0. -1.  0.  0.  0.]
 [ 0. -1.  0. -1.  0.  0.]
 [ 0.  0. -1.  0. -1.  0.]
 [ 0.  0.  0. -1.  0. -1.]
 [-1.  0.  0.  0. -1.  0.]]


In [10]:
E,V=eig(H)

In [11]:
print(E)

[-2. -1. -1.  1.  1.  2.]


In [12]:
print(V)

[[ 0.40824829  0.57245374  0.07503368  0.57735027 -0.09791921  0.40824829]
 [ 0.40824829  0.22124579  0.53327632 -0.28867513 -0.4437968  -0.40824829]
 [ 0.40824829 -0.35120794  0.45824264 -0.28867513  0.54171601  0.40824829]
 [ 0.40824829 -0.57245374 -0.07503368  0.57735027 -0.09791921 -0.40824829]
 [ 0.40824829 -0.22124579 -0.53327632 -0.28867513 -0.4437968   0.40824829]
 [ 0.40824829  0.35120794 -0.45824264 -0.28867513  0.54171601 -0.40824829]]
